# Generated by Django 2.2.3 on 2019-09-09 06:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0019_data_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowlevel2',
            name='edit_date',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now, verbose_name='Last Edit Date'),
            preserve_default=False,
        ),
    ]
